### ISSUE TITLE
cannot run example scripts using BO code in python2.7, 3.4 and 3.5

### ISSUE THREAD

**Issue by adhaka** [elfi-dev/elfi#256]
#### Summary:
When I tried to run the example scripts in the examples folder:

python  bdm.py

I get this error:

  File "/home/akash/anaconda2/envs/py34/lib/python3.4/site-packages/elfi/methods/bo/utils.py", line 76
    start_points[:, i] = random_state.uniform(*bounds[i], n_start_points)
                                                                     ^
SyntaxError: only named arguments may follow *expression

I got this error both in 2.7 and 3.4. After this I tried to create a new environment and installed 3.5 virtually on anaconda, and tried to run it again, and this time I got this:
  File "/home/akash/SheffieldML/GPy/core/parameterization/__init__.py", line 9, in <module>
    from paramz import ties_and_remappings, ObsAr
ImportError: cannot import name 'ties_and_remappings'

This is a GPy Error, because one of the dependency pacjkages: paramz is still uncompatible for python 3.5. Can you suggest something here which I should do with the installations to make it finally working. 

#### Current Output:
The example scripts did not run and throw syntax errors.

#### Expected Output:
The example scripts did not run.

**Comment by vuolleko** [comment]
Hi,

ELFI requires Python 3.5 or greater, so your first 2 attempts were doomed because of that. :)

For the third one, did you follow the [installation instruction](http://elfi.readthedocs.io/en/latest/installation.html)? Which versions of GPy and Paramz did you install? At least more recent versions of Paramz work fine with Python 3.5+.

**Comment by adhaka** [comment]
Yeah, ok I actually just used the pip version of paramz and GPy with 3.5, I will try to install them by specifying the version this time.

**Comment by adhaka** [comment]
I finally installed it properly, I had some older version of GPy- 1.5 in the source directory which was throwing up errors, updating it to the latest version made everything fine.
